# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres:11
    restart: always
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
