# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    build: 
      context: ./postgres
    restart: always
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/user:/userdata
    ports: 
      - "5432:5432"
